### ISSUE TITLE
只支持lua-5.3.4及以上的版本

### ISSUE THREAD

**Issue by Patrick08T** [esrrhs/pLua#3]
执行: `g++ -g3 -shared -o libplua.so plua.cpp -fPIC -std=c++11 -I ../lua-5.3.1/include/`

报错如下:
plua.cpp: 在函数‘int pushglobalfuncname(lua_State*, lua_Debug*)’中:
plua.cpp:117:40: 错误：‘LUA_LOADED_TABLE’在此作用域中尚未声明
     lua_getfield(L, LUA_REGISTRYINDEX, LUA_LOADED_TABLE);

请问大佬后续会做低版本兼容吗?

**Comment by esrrhs** [comment]
@Patrick08T 这个代码属于从lua中copy来的，看看copy from lua的字样。低版本的lua应该也支持的，你改成你的lua版本即可，这段代码的目的是去拿堆栈的函数名

**Comment by Patrick08T** [comment]
LUA_LOADED_TABLE 这个是lua-5.3.4 中加入的, 升级之后问题已解决

**Comment by cj2a7t** [comment]
luajit
<img width="749" alt="image" src="https://github.com/esrrhs/pLua/assets/70355872/e1647a0c-519e-467e-adad-32f5afce3f20">

**Comment by cj2a7t** [comment]
Hi @esrrhs 请教个问题。 luajit使用时，LuaJIT的JIT编译器在处理信号和钩子时，LUA_MASKCOUNT行为与标准的Lua解释器不一样，这个有什么思路解决不。
